activities = [
{"activity_id": "1",
"description":"A fun and competitive game of tennis",
"level_of_flexibility":"Specific date",
"location":"Quincy Park, Arlington, Virginia",
"maxParticipants":5,
"minParticipants":3,
"name":"Tennis Titans at Quincy",
"scheduledAt":"This Wednesday",
"status":"completed",
"type":"Outdoor Sports",
"preferredUsers": ["Rafael", "Novak"]
},

{
"activity_id": "2",
"description": "A fun and adventurous hiking activity",
"level_of_flexibility":"Flexible",
"location": "W&OD Trail in Shirlington, VA",
"maxParticipants": 5,
"minParticipants": 3,
"name": "Arlington Adventure Hike",
"scheduledAt": "N/A",
"status": "completed",
"type": "Outdoor Activity",
"preferredUsers": ["Thaddeus", "Sohom"]
},

{"activity_id": "3",
"description":"Watching a basketball game",
"level_of_flexibility":"specific date and time",
"location":"Dudleys in Shirlington, Virginia",
"maxParticipants":5,
"minParticipants":3,
"name":"Saturday Hoops at Dudley's",
"scheduledAt":"this Saturday at 7 pm",
"status":"completed",
"type":"Watching sports",
"preferredUsers": []
},
{"activity_id": "4",
"description":"Bowling activity",
"level_of_flexibility":"Low",
"location":"Lucky Strike Tysons Corner",
"maxParticipants":5,
"minParticipants":4,
"name":"Friday Night Strikes",
"scheduledAt":"This Friday at 7:30 pm",
"status":"completed",
"type":"Bowling",
"preferredUsers": ["Alex", "Derek"]},

{"activity_id": "5",
 "description":"A fun-filled trivia night with friends.",
 "level_of_flexibility":"Low",
 "location":"Arlington, Virginia",
 "maxParticipants":4,
 "minParticipants":3,
 "name":"Friday Night Trivia Challenge",
 "scheduledAt":"Friday night",
 "status":"completed",
 "type":"Bar Game",
 "preferredUsers": ["Ken","James"]}
]